---
# right now, all networks here should be bridged
networks:
  - name: osbr0 # you were using controllerNetwork
    subnet: 192.168.52.0/24
    gateway: 192.168.52.254
    device: osbr0 # defaults to the name of the network, if not present
  - name: osbr1 # device should be the same as the name
    subnet: 10.0.0.0/16
    gateway: 10.0.255.254
